GET http://localhost:3001/users/email/martinzaratustra@gmail.com


# POST http://localhost:3001/users/

# Content-Type: application/json

# {
# "price":5,
# "quantity":23,
# "state":"carrito",
# "userId":1
# }